name: Code Style

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        if: github.event.pull_request.draft == false

        steps:
            -   name: Checkout
                uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            -   name: Setup PHP
                uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
                with:
                    php-version: '8.3'
                    coverage: none # disable xdebug, pcov
                    tools: cs2pr

            -   name: Composer install
                uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

            -   name: Run php-cs-fixer
                run: vendor/bin/php-cs-fixer check --ansi --diff --format=checkstyle | cs2pr
